name = "maxmouchet"
repo = "https://github.com/maxmouchet/JuliaRegistry.git"
uuid = "c7f9ddcf-1f9c-4e56-b7b0-525f8cf92dbd"
description = ""

[packages.212d6d54-436c-11e9-27d8-f17facaf9a93]
name = "ClickHouse"
path = "packages/ClickHouse"

[packages.b2df20ec-1dc9-4c70-9a34-3aba712a2ea4]
name = "Statistikk"
path = "packages/Statistikk"

[packages.b2b3ca75-8444-5ffa-85e6-af70e2b64fe7]
name = "HMMBase"
path = "packages/HMMBase"

[packages.d69f1d75-0f53-4bd4-8114-76337d5140b8]
name = "HDPHMM"
path = "packages/HDPHMM"

[packages.b8100c8c-14fe-11e9-0588-c112a69d043d]
name = "RTTHMM"
path = "packages/RTTHMM"

[packages.be869012-f1ee-4d1b-ac0c-66b7016f7c90]
name = "VHEM"
path = "packages/VHEM"
