name = "maxmouchet/JuliaRegistry"
uuid = "c7f9ddcf-1f9c-4e56-b7b0-525f8cf92dbd"
repo = "https://github.com/maxmouchet/JuliaRegistry.git"

description = ""

[packages]
b2b3ca75-8444-5ffa-85e6-af70e2b64fe7 = { name = "HMMBase", path = "HMMBase" }
d69f1d75-0f53-4bd4-8114-76337d5140b8 = { name = "HDPHMM", path = "HDPHMM" }