name = "maxmouchet"
repo = "https://github.com/maxmouchet/JuliaRegistry.git"
uuid = "c7f9ddcf-1f9c-4e56-b7b0-525f8cf92dbd"
description = ""

[packages.f257ca76-8b9a-11e8-0bde-f976b35185a3]
name = "InternetMeasurements"
path = "InternetMeasurements"

[packages.b2b3ca75-8444-5ffa-85e6-af70e2b64fe7]
name = "HMMBase"
path = "HMMBase"

[packages.87b67ed6-8c2d-11e8-02b9-dd58cea78357]
name = "PyIP"
path = "PyIP"

[packages.d69f1d75-0f53-4bd4-8114-76337d5140b8]
name = "HDPHMM"
path = "HDPHMM"

[packages.b8100c8c-14fe-11e9-0588-c112a69d043d]
name = "RTTHMM"
path = "RTTHMM"

[packages.212d6d54-436c-11e9-27d8-f17facaf9a93]
name = "ClickHouse"
path = "ClickHouse"
